version: "3.0"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      WEBPASSWORD: $piholepass
      DNS1: '9.9.9.9'
      DNSSEC: 'True'
      ServerIP: '192.168.86.44'
    # Volumes store your data between container upgrades
    volumes:
      - /Users/hartrussell/pihole/etc:/etc/pihole/'
      - /Users/hartrussell/pihole/dnsmasq:/etc/dnsmasq.d/'
    #dns:
    #  - 127.0.0.1
     # - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    command: --interval 30000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: bridge
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - VERSION=docker
      - PLEX_CLAIM=claim-ywr8352J97ie31PdX6qE
    volumes:
      - /Users/hartrussell/Plex/config:/config
      - /Volumes/SuperSickFolder/Television:/tv
      - /Volumes/SuperSickFolder/Movies:/movies
    restart: unless-stopped
      
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    network_mode: service:vpn
    depends_on:
      - vpn
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /Users/hartrussell/Transmission/config:/config
      - /Volumes/Storage/Downloads:/downloads
      - /Users/hartrussell/Transmission/watch:/watch
    restart: unless-stopped
    
  vpn:
    image: bubuntux/nordvpn:latest
    container_name: NordVPN_Gateway
    network_mode: bridge
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    sysctls:
      - net.ipv4.conf.eth0.rp_filter=2
    devices:
      - /dev/net/tun
    environment:
      - USER=$nordemail
      - PASS=$nordpassword
      - CONNECT=United_States 
      - TECHNOLOGY=NordLynx
      - NETWORK=192.168.1.0/24
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
      
